GET http://127.0.0.1:5000/items
###

POST http://localhost:5000/item/a
Authorization:JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTA2OTgwMzIsImlhdCI6MTYxMDY5NzczMiwibmJmIjoxNjEwNjk3NzMyLCJpZGVudGl0eSI6MX0.nWYqPlKs8B2K2hd5AJiNZAgKJfEIy2KhOABgZ49oNrM
Content-Type: application/json
# body:

{
    "price":12.99
}


###
GET http://127.0.0.1:5000/item/a
Authorization:JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTA2OTgwMzIsImlhdCI6MTYxMDY5NzczMiwibmJmIjoxNjEwNjk3NzMyLCJpZGVudGl0eSI6MX0.nWYqPlKs8B2K2hd5AJiNZAgKJfEIy2KhOABgZ49oNrM
###
POST http://127.0.0.1:5000/auth
Content-Type: application/json

{
    "username":"bob",
    "password":"asdf"
}

###
DELETE http://127.0.0.1:5000/item/f

### 
PUT http://127.0.0.1:5000/item/d
Content-Type: application/json

{
    
    "price":720
   
}
###
POST http://127.0.0.1:5000/register
Content-Type: application/json

{
    "username":"bob",
    "password":"asdf"
}

