
@url=http://127.0.0.1:5000
@token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTA5NzQ0MDMsImlhdCI6MTYxMDk3NDEwMywibmJmIjoxNjEwOTc0MTAzLCJpZGVudGl0eSI6MX0.LMLjVmGCMBeb2zdPLgAMlMCNhxMWcfFEpJqbBB6Youg
###
GET {{url}}/items
###

POST http://localhost:5000/item/d
Authorization:JWT {{token}}
Content-Type: application/json
# body:

{
    "price":12.99
}


###
GET http://127.0.0.1:5000/item/c
Authorization:JWT {{token}}
###

DELETE http://127.0.0.1:5000/item/b

### 
PUT http://127.0.0.1:5000/item/d
Content-Type: application/json

{
    
    "price":720
   
}
###


POST http://127.0.0.1:5000/auth
Content-Type: application/json

{
    "username":"bob",
    "password":"asdf"
}

###
POST http://127.0.0.1:5000/register
Content-Type: application/json

{
    "username":"bob",
    "password":"asdf"
}

