GET http://127.0.0.1:5000/items
###

POST http://localhost:5000/item/a
Authorization:JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTA1Mjc4MzcsImlhdCI6MTYxMDUyNzUzNywibmJmIjoxNjEwNTI3NTM3LCJpZGVudGl0eSI6MX0.n6yKBFqup8vzZMtgpZdiStzLbiFxE7Hd4MtJWPpXLRc
Content-Type: application/json
# body:

{
    "price":12.99
}


###
GET http://127.0.0.1:5000/item/test
Authorization:JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTA1Mjc4MzcsImlhdCI6MTYxMDUyNzUzNywibmJmIjoxNjEwNTI3NTM3LCJpZGVudGl0eSI6MX0.n6yKBFqup8vzZMtgpZdiStzLbiFxE7Hd4MtJWPpXLRc
###
POST http://127.0.0.1:5000/auth
Content-Type: application/json

{
    "username":"bob",
    "password":"asdf"
}

###
DELETE http://127.0.0.1:5000/item/b

### 
PUT http://127.0.0.1:5000/item/d
Content-Type: application/json

{
    
    "price":720
   
}
###
POST http://127.0.0.1:5000/register
Content-Type: application/json

{
    "username":"bob",
    "password":"asdf"
}